storage:
  enabled: true
  requests: 128Mi # Set as desired

extraArgs:
  - --dbfilename=dump.rdb
  - --snapshot_cron=* * * * * # cron format

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000