---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: decidim-token
            key: decidim-token
