---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zalando
spec:
  interval: 30m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
