---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
 name: vault-decidim
 namespace: vault
spec:
 provider:
  vault:
   server: "https://vault.acme.org"
   path: "secret"
   version: "v2"
   auth:
    tokenSecretRef:
     name: "vault-token"
     key: "vault-token"
