apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: decidim
spec:
  secretStoreRef:
    kind: SecretStore
    name: secrets

  target:
    name: decidim

  dataFrom:
    - find:
        name:
          regexp: .*