---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: secret-external
spec:
 refreshInterval: "15s"
 secretStoreRef:
  name: vault-decidim
  kind: SecretStore
 target:
  name: secret-external
 data:
  - secretKey: user
    remoteRef:
     key: kv/decidim
     property: user
